#!/bin/bash

cd kl25z128
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../kl25z128 && cp *.srec ../../kl25z128
cd ..

cd lm4f120
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../lm4f120
cd ..

cd lm4f232
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../lm4f232
cd ..

cd tm4c1294
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../tm4c1294
cd ..

cd stm32f1
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../stm32f1
cd ..

cd stm32f4
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../stm32f4
cd ..

cd stm32f429
make clean all && ls -l *.bin && md5sum *.bin && cp *.bin ../../stm32f429
cd ..

# Intel Hex images for STM targets:

cd ..

cd stm32f1
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f1.bin mecrisp-stellaris-stm32f1.hex
cd ..

cd stm32f4
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f4.bin mecrisp-stellaris-stm32f4.hex
cd ..

cd stm32f429
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f429.bin mecrisp-stellaris-stm32f429.hex
cd ..
